import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Home.module.css'
import Layout from '../component/Layout';
import MailchimpAuto from '../component/MailchimpAuto'; 
import Mailchimp from '../component/Mailchimp'; 


export default function Home() {

  const [isAuto, setIsAuto] = useState(true);

  const handleSwitch = () => {
    setIsAuto(!isAuto);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>My Mailchimp</title>
        <meta name="description" content="Generated by create next app" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Layout isAuto={isAuto} handleSwitch={handleSwitch}>
          {isAuto ? <MailchimpAuto /> :  <Mailchimp />}
        </Layout>
      </main>
    </div>
  )
}
